src/Form/Type/ReCaptchaType.php
<?php

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReCaptchaType extends AbstractType
{
    /**
     * The reCAPTCHA server URL's.
     */
    private const RECAPTCHA_API_SERVER = 'https://www.google.com/recaptcha/api.js';
    private const RECAPTCHA_API_JS_SERVER = '//www.google.com/recaptcha/api/js/recaptcha_ajax.js';

    /**
     * The public key.
     *
     * @var string
     */
    protected $publicKey;

    /**
     * Enable recaptcha?
     *
     * @var bool
     */
    protected $enabled;

    /**
     * Use AJAX api?
     *
     * @var bool
     */
    protected $ajax;

    /**
     * @param string $publicKey Recaptcha public key
     * @param bool   $enabled   Recaptcha status
     * @param bool   $ajax      Ajax status
     */
    public function __construct($publicKey, $enabled, $ajax)
    {
        $this->publicKey = $publicKey;
        $this->enabled = $enabled;
        $this->ajax = $ajax;
    }

    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars = array_replace(
            $view->vars,
            [
                'recaptcha_enabled' => $this->enabled,
                'recaptcha_ajax' => $this->ajax,
            ]
        );
        if (!$this->enabled) {
            return;
        }

        if (!isset($options['language'])) {
            $options['language'] = $this->resolveLocale();
        }

        if (!$this->ajax) {
            $view->vars = array_replace(
                $view->vars,
                [
                    'url_challenge' => sprintf('%s?hl=%s', self::RECAPTCHA_API_SERVER, $options['language']),
                    'public_key' => $this->publicKey,
                ]
            );
        } else {
            $view->vars = array_replace(
                $view->vars,
                [
                    'url_api' => self::RECAPTCHA_API_JS_SERVER,
                    'public_key' => $this->publicKey,
                ]
            );
        }
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'compound' => false,
                'language' => $this->resolveLocale(),
                'public_key' => null,
                'url_challenge' => null,
                'url_noscript' => null,
                'attr' => [
                    'options' => [
                        'theme' => 'light',
                        'type' => 'image',
                        'size' => 'normal',
                        'callback' => null,
                        'expiredCallback' => null,
                        'bind' => null,
                        'defer' => false,
                        'async' => false,
                        'badge' => null,
                    ],
                ],
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return TextType::class;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'recaptcha';
    }

    /**
     * Get the current locale.
     *
     * @return string
     */
    public function resolveLocale()
    {
        return 'en';
    }
}

templates/theme_admin1/board-list.html.twig
{# Reference: https://stackoverflow.com/questions/40707461/recursive-macro-in-twig #}
{% macro recursiveCategory(category, level) %}
    {% import _self as self %}
    {% set level = level|default(0) %}
    <ul class="list-unstyled">
        <li class="media {% if level > 0 %}mt-3{% endif %}">
            <img class="mr-3" src="https://placehold.it/64x64" alt="Image">
            <div class="media-body">
                <h5 class="mt-0">{{ category.title }} (ID: {{ category.id }})</h5>
                {{ category.description }}
                {% if category.boards|length %}
                    {% for child in category.boards %}
                        {{ self.recursiveCategory(child, level + 1) }}
                    {% endfor %}
                {% endif %}
            </div>
        </li>
    </ul>
{% endmacro %}
{% import _self as self %}

{% extends 'theme_admin1/layout_admin.html.twig' %}

{% block breadcrumb %}
    <div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20">
        <ul class="u-list-inline g-color-gray-dark-v6">

            <li class="list-inline-item">
                <span class="g-valign-middle">{{ 'admin.page.board_list.breadcrumb.forum'|trans }}</span>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div class="g-pa-20">
        <h1 class="g-font-weight-300 g-font-size-28 g-color-black g-mb-40">{{ 'admin.page.board_list.title'|trans }}</h1>

        <a href="{{ path('forum_admin', {'forum': current_forum.url, 'page': 'new-board'}) }}" class="btn btn-success mb-3">{{ 'admin.page.board_list.create'|trans }}</a>
        <div class="card">
            <div class="card-body">
                {% for board in board_list %}
                    {{ self.recursiveCategory(board) }}
                {% endfor %}
            </div>
        </div>
        <a href="{{ path('forum_admin', {'forum': current_forum.url, 'page': 'new-board'}) }}" class="btn btn-success mt-3">{{ 'admin.page.board_list.create'|trans }}</a>
    </div>
{% endblock %}

templates/theme_admin1/home.html.twig
{% extends 'theme_admin1/layout_admin.html.twig' %}

{% block breadcrumb %}
    <div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20">
        <ul class="u-list-inline g-color-gray-dark-v6">

            <li class="list-inline-item">
                <span class="g-valign-middle">{{ 'admin.page.home.breadcrumb.home'|trans }}</span>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div class="g-pa-20">
        <h1 class="g-font-weight-300 g-font-size-28 g-color-black g-mb-40">{{ 'admin.page.home.title'|trans }}</h1>
    </div>
{% endblock %}

templates/theme_admin1/new-board.html.twig
{% extends 'theme_admin1/layout_admin.html.twig' %}

{% form_theme create_board_form 'form/admin-choice.html.twig' %}

{% block breadcrumb %}
    <div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20">
        <ul class="u-list-inline g-color-gray-dark-v6">

            <li class="list-inline-item g-mr-10">
                <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="#!">{{ 'admin.page.new_board.breadcrumb.board'|trans }}</a>
                <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
            </li>

            <li class="list-inline-item">
                <span class="g-valign-middle">{{ 'admin.page.new_board.breadcrumb.create'|trans }}</span>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div class="g-pa-20">
        <h1 class="g-font-weight-300 g-font-size-28 g-color-black g-mb-40">{{ 'admin.page.new_board.title'|trans }}</h1>

        {% for message in app.session.flashbag.get('board_added') %}
            <div class="alert alert-success fade in alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ 'admin.page.new_board.board_added'|trans }}
            </div>
        {% endfor %}
        {% for message in app.session.flashbag.get('board_not_added') %}
            <div class="alert alert-danger fade in alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ 'admin.page.new_board.board_not_added'|trans }}
            </div>
        {% endfor %}

        <div class="row">
            <div class="col-lg-6">
                {{ form_start(create_board_form, {'attr': {'class': 'card'}}) }}
                <div class="card-header">{{ 'admin.page.new_board.block1.title'|trans }}</div>
                <div class="card-body">
                    {{ form_errors(create_board_form) }}

                    <div class="form-group row">
                        {{ form_label(create_board_form.name, null, {'label_attr': {'class': 'col-sm-4 col-form-label'}}) }}
                        <div class="col-sm-8">
                            {{ form_widget(create_board_form.name, {'attr': {'class': 'form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-4 g-px-14 g-py-10'}}) }}
                            <small class="form-text">{{ 'admin.form.create_board.name.help'|trans }}</small>
                            <small class="form-text text-danger">{{ form_errors(create_board_form.name) }}</small>
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ form_label(create_board_form.description, null, {'label_attr': {'class': 'col-sm-4 col-form-label'}}) }}
                        <div class="col-sm-8">
                            {{ form_widget(create_board_form.description, {'attr': {'class': 'form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-4 g-px-14 g-py-10'}}) }}
                            <small class="form-text">{{ 'admin.form.create_board.description.help'|trans }}</small>
                            <small class="form-text text-danger">{{ form_errors(create_board_form.description) }}</small>
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ form_label(create_board_form.parent, null, {'label_attr': {'class': 'col-sm-4 col-form-label'}}) }}
                        <div class="col-sm-8">
                            <div class="form-group u-select--v3 g-pos-rel g-brd-gray-light-v7 g-rounded-4 mb-0">
                                {{ form_widget(create_board_form.parent, {'attr': {'class': 'js-select u-select--v3-select u-sibling w-100'}}) }}
                                <div class="d-flex align-items-center g-absolute-centered--y g-right-0 g-color-gray-light-v6 g-color-lightblue-v9--sibling-opened g-mr-15">
                                    <i class="hs-admin-angle-down"></i>
                                </div>
                            </div>
                            <small class="form-text">{{ 'admin.form.create_board.parent.help'|trans }}</small>
                            <small class="form-text text-danger">{{ form_errors(create_board_form.parent) }}</small>
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ form_label(create_board_form.type, null, {'label_attr': {'class': 'col-sm-4 col-form-label'}}) }}
                        <div class="col-sm-8">

                            <div class="btn-group justified-content">
                                {% for key, type in create_board_form.type %}
                                    <label class="u-check">
                                        {{ form_widget(type, {'attr': {'class': 'g-hidden-xs-up g-pos-abs g-top-0 g-left-0'}}) }}
                                        <span class="btn btn-md btn-block u-btn-outline-lightgray g-color-white--checked g-bg-primary--checked rounded-0">
                                            {{ type.vars.label|trans }}
                                        </span>
                                    </label>
                                {% endfor %}
                            </div>

                            <small class="form-text">{{ 'admin.form.create_board.type.help'|trans }}</small>
                            <small class="form-text text-danger">{{ form_errors(create_board_form.type) }}</small>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    {{ form_widget(create_board_form.send, {'attr': {'class': 'btn btn-success btn-block'}}) }}
                </div>
                {{ form_end(create_board_form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/theme_admin1/not-found.html.twig
{% extends 'theme_admin1/layout_admin.html.twig' %}

{% block content %}
    <div class="g-pa-20">
        <h1 class="g-font-weight-300 g-font-size-28 g-color-black g-mb-40">{{ 'admin.page.not_found.title'|trans }}</h1>
        <p>{{ 'admin.page.not_found.text'|trans }}</p>
    </div>
{% endblock %}