src/Entity/Board.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="forum_boards")
 */
class Board
{
    public const TYPE_BOARD = 1;
    public const TYPE_CATEGORY = 2;

    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @var Forum
     * @ORM\ManyToOne(targetEntity="Forum", inversedBy="boards")
     * @ORM\JoinColumn(name="forum_id", referencedColumnName="id", nullable=false)
     */
    protected $forum;

    /**
     * @var Board|null
     * @ORM\ManyToOne(targetEntity="Board", inversedBy="boards")
     * @ORM\JoinColumn(name="parent_board_id", referencedColumnName="id")
     */
    protected $parent_board;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $title;

    /**
     * @var string|null
     * @ORM\Column(type="string", nullable=true)
     */
    protected $description;

    /**
     * @var int
     * @ORM\Column(type="smallint")
     */
    protected $type;

    /**
     * @var User|null
     * @ORM\ManyToOne(targetEntity="\App\Entity\User")
     * @ORM\JoinColumn(name="last_post_user_id", referencedColumnName="id")
     */
    protected $last_post_user;

    /**
     * @var DateTime|null
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $last_post_time;

    /**
     * @var int
     * @ORM\Column(type="integer", options={"default": 0})
     */
    protected $thread_count = 0;

    /**
     * @var int
     * @ORM\Column(type="integer", options={"default": 0})
     */
    protected $post_count = 0;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="Board", mappedBy="parent_board", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    protected $boards;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="Thread", mappedBy="board", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    protected $threads;

    public function __construct()
    {
        $this->boards = new ArrayCollection();
        $this->threads = new ArrayCollection();
    }

    /**
     * @return int The ID
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return Forum The forum
     */
    public function getForum(): Forum
    {
        return $this->forum;
    }

    /**
     * @param Forum $forum The forum
     *
     * @return $this
     */
    public function setForum(Forum $forum): self
    {
        $this->forum = $forum;

        return $this;
    }

    /**
     * @return Board|null The parent board or null if already the top-most board
     */
    public function getParentBoard(): ?self
    {
        return $this->parent_board;
    }

    /**
     * @param Board|null $parent_board The parent board or null if already the top-most board
     *
     * @return $this
     */
    public function setParentBoard(self $parent_board = null): self
    {
        $this->parent_board = $parent_board;

        return $this;
    }

    /**
     * @return string The title
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * @param string $title The title
     *
     * @return $this
     */
    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string|null The description
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string|null $description The description
     *
     * @return $this
     */
    public function setDescription(string $description = null): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return int The type
     */
    public function getType(): int
    {
        return $this->type;
    }

    /**
     * @param int $type The type
     *
     * @return $this
     */
    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return User|null The use who last posted
     */
    public function getLastPostUser(): ?User
    {
        return $this->last_post_user;
    }

    /**
     * @param User|null $last_post_user The user who last posted
     *
     * @return $this
     */
    public function setLastPostUser(User $last_post_user = null): self
    {
        $this->last_post_user = $last_post_user;

        return $this;
    }

    /**
     * @return DateTime|null The last time somebody posted
     */
    public function getLastPostTime(): ?DateTime
    {
        return $this->last_post_time;
    }

    /**
     * @param DateTime|null $last_post_time The last time somebody posted
     *
     * @return $this
     */
    public function setLastPostTime(DateTime $last_post_time = null): self
    {
        $this->last_post_time = $last_post_time;

        return $this;
    }

    /**
     * @return int The number of threads
     */
    public function getThreadCount(): int
    {
        return $this->thread_count;
    }

    /**
     * @param int $threads The number of threads
     *
     * @return $this
     */
    public function setThreadCount(int $threads): self
    {
        $this->thread_count = $threads;

        return $this;
    }

    /**
     * @return int The number of posts
     */
    public function getPostCount(): int
    {
        return $this->post_count;
    }

    /**
     * @param int $posts The number of posts
     *
     * @return $this
     */
    public function setPostCount(int $posts): self
    {
        $this->post_count = $posts;

        return $this;
    }

    /**
     * @return Thread[] The threads
     */
    public function getThreads(): array
    {
        return $this->threads->toArray();
    }

    /**
     * @param Thread $thread The thread
     *
     * @return $this
     */
    public function addThread(Thread $thread): self
    {
        $this->threads->add($thread);
        $thread->setBoard($this);

        return $this;
    }

    /**
     * @param Thread $thread The thread
     *
     * @return $this
     */
    public function removeThread(Thread $thread): self
    {
        if ($this->threads->contains($thread)) {
            $this->threads->removeElement($thread);
        }

        return $this;
    }

    /**
     * @return Board[] The boards
     */
    public function getBoards(): array
    {
        return $this->boards->toArray();
    }

    /**
     * @param Board $board The board
     *
     * @return $this
     */
    public function addBoard(self $board): self
    {
        $this->boards->add($board);
        $board->setParentBoard($this);

        return $this;
    }

    /**
     * @param Board $board The board
     *
     * @return $this
     */
    public function removeBoard(self $board): self
    {
        if ($this->boards->contains($board)) {
            $this->boards->removeElement($board);
        }

        return $this;
    }

    /**
     * @return array An array of all the properties of an object
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'forum' => $this->forum,
            'parent_board' => $this->parent_board,
            'title' => $this->title,
            'description' => $this->description,
            'type' => $this->type,
            'last_post_user' => $this->last_post_user,
            'last_post_time' => $this->last_post_time,
            'threads' => $this->thread_count,
            'posts' => $this->post_count,
        ];
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use DateTime;
use Decoda\Decoda;
use Decoda\Hook\EmoticonHook;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="forum_posts")
 */
class Post
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @var Thread
     * @ORM\ManyToOne(targetEntity="Thread", inversedBy="posts")
     * @ORM\JoinColumn(name="thread_id", referencedColumnName="id", nullable=false)
     */
    protected $thread;

    /**
     * @var int
     * @ORM\Column(type="integer")
     */
    protected $post_number;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="\App\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    protected $user;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $subject;

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    protected $message;

    /**
     * @var DateTime
     * @ORM\Column(type="datetime")
     */
    protected $created_on;

    /**
     * @return int The ID
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return Thread The thread
     */
    public function getThread(): Thread
    {
        return $this->thread;
    }

    /**
     * @param Thread $thread The thread
     *
     * @return $this
     */
    public function setThread(Thread $thread): self
    {
        $this->thread = $thread;

        return $this;
    }

    /**
     * @return int The number of posts
     */
    public function getPostNumber(): int
    {
        return $this->post_number;
    }

    /**
     * @param int $post_number The number of posts
     *
     * @return $this
     */
    public function setPostNumber(int $post_number): self
    {
        $this->post_number = $post_number;

        return $this;
    }

    /**
     * @return User The user
     */
    public function getUser(): User
    {
        return $this->user;
    }

    /**
     * @param User $user The user
     *
     * @return $this
     */
    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return string The subject
     */
    public function getSubject(): string
    {
        return $this->subject;
    }

    /**
     * @param string $subject The subject
     *
     * @return $this
     */
    public function setSubject(string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * @return string The message
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * @return string The formatted message
     */
    public function getFormattedMessage(): string
    {
        $bbParser = new Decoda($this->message);
        $bbParser->defaults();
        $bbParser->addHook(new EmoticonHook());

        return $bbParser->convertLineBreaks($bbParser->parse());
    }

    /**
     * @param string $message The message
     *
     * @return $this
     */
    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    /**
     * @return DateTime The date when the post was created
     */
    public function getCreatedOn(): DateTime
    {
        return $this->created_on;
    }

    /**
     * @param DateTime $created_on The date when the post was created
     *
     * @return $this
     */
    public function setCreatedOn(DateTime $created_on): self
    {
        $this->created_on = $created_on;

        return $this;
    }

    /**
     * @return array An array of all the properties of an object
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'thread' => $this->thread,
            'post_number' => $this->post_number,
            'user' => $this->user,
            'subject' => $this->subject,
            'message' => $this->message,
            'created_on' => $this->created_on,
        ];
    }
}

templates/theme1/index.html.twig
{% extends 'theme1/layout.html.twig' %}

{% set service_page_links %}
    {% for text,link in current_forum.links %}
        <li class="nav-item"><a href="{{ link }}" class="nav-link">{{ text }}</a></li>
    {% endfor %}
{% endset %}
{% set service = {
    'page_name': current_forum.name,
    'page_logo_link': '/' ~ current_forum.url,
    'page_author': current_forum.owner.username,
    'page_description': current_forum.description,
    'page_keywords': current_forum.keywords|join(','),
    'page_links': service_page_links,
    'page_google_webdev': current_forum.googleWebDeveloper,
    'page_ga_id': current_forum.googleAnalyticsId,
    'page_logo_url': ''
} %}

{% block title %}{{ 'service_index.title'|trans }} | {{ service.page_name }}{% endblock %}

{% block header %}
    <div class="container">
        <h1 class="mt-4 mb-2 pb-2 border-bottom">{{ current_forum.name }}</h1>
    </div>
{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">{{ 'service_index.breadcrumb.home'|trans }}</li>
            </ol>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% if board_tree|length == 0 %}
            <hr />
            <div class="alert alert-danger" role="alert">
                {{ 'service_index.no_board'|trans }}
            </div>
        {% else %}
            {% for board in board_tree %}
                {% if board.type == 2 and board.parentBoard is null %}
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover table-sm">
                            <thead>
                            <tr>
                                <th class="text-center" width="56%">{{ board.title }}</th>
                                <th class="text-center" width="7%" >{{ 'service_index.table.topics'|trans }}</th>
                                <th class="text-center" width="7%">{{ 'service_index.table.posts'|trans }}</th>
                                <th class="text-center" width="30%">{{ 'service_index.table.last_post'|trans }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% if board.boards|length > 0 %}
                                {% for subboard in board.boards %}
                                    <tr>
                                        <td class="forum-category">
                                            <p><a href="{{ path('forum_board', {'forum': current_forum.url, 'board': subboard.id}) }}">{{ subboard.title }}</a></p>
                                            <p>{{ subboard.description }}</p>
                                        </td>
                                        <td class="text-center"><br /><span class="badge badge-secondary">{{ subboard.threadCount }}</span></td>
                                        <td class="text-center"><br /><span class="badge badge-secondary">{{ subboard.postCount }}</span></td>
                                        <td>
                                            {% if subboard.lastPostUser is not null %}
                                                <p>
                                                    <i>{{ 'service_index.table.last_post'|trans }}</i> {{ 'service_index.table.by'|trans }}
                                                    <a href="{{ path('user', {'username': subboard.lastPostUser.username}) }}">{{ subboard.lastPostUser.username }}</a>
                                                </p>
                                                <p>{{ subboard.lastPostTime|date('d/m/Y H:i') }}</p>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                {% endif %}
            {% endfor %}

            {# Check if there is a board without a category #}
            {% set counter = 0 %}
            {% for board in board_tree %}
                {% if board.type == 1  %}
                    {% set counter = counter + 1 %}
                {% endif %}
            {% endfor %}
            {# Get all boards without category #}
            {% if counter > 0 %}
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover table-sm">
                        <thead>
                        <tr>
                            <th class="text-center" width="56%">{{ 'service_index.table.boards'|trans }}</th>
                            <th class="text-center" width="7%" >{{ 'service_index.table.topics'|trans }}</th>
                            <th class="text-center" width="7%">{{ 'service_index.table.posts'|trans }}</th>
                            <th class="text-center" width="30%">{{ 'service_index.table.last_post'|trans }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for board in board_tree %}
                            {% if board.type == 1 %}
                                <tr>
                                    <td class="forum-category">
                                        <p><a href="{{ path('forum_board', {'forum': current_forum.url, 'board': board.id}) }}">{{ board.title }}</a></p>
                                        <p>{{ board.description }}</p>
                                    </td>
                                    <td class="text-center"><br /><span class="badge badge-secondary">{{ board.threadCount }}</span></td>
                                    <td class="text-center"><br /><span class="badge badge-secondary">{{ board.postCount }}</span></td>
                                    <td>
                                        {% if board.lastPostUser is not null %}
                                            <p>
                                                <i>{{ 'service_index.table.last_post'|trans }}</i> {{ 'service_index.table.by'|trans }}
                                                <a href="{{ path('user', {'username': board.lastPostUser.username}) }}">{{ board.lastPostUser.username }}</a>
                                            </p>
                                            <p>{{ board.lastPostTime|date('d/m/Y H:i') }}</p>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

templates/theme1/thread.html.twig
{% extends 'theme1/layout.html.twig' %}

{% set service_page_links %}
    {% for text,link in current_forum.links %}
        <li class="nav-item"><a href="{{ link }}" class="nav-link">{{ text }}</a></li>
    {% endfor %}
{% endset %}
{% set service = {
    'page_name': current_forum.name,
    'page_logo_link': '/' ~ current_forum.url,
    'page_author': current_forum.owner.username,
    'page_description': current_forum.description,
    'page_keywords': current_forum.keywords|join(','),
    'page_links': service_page_links,
    'page_google_webdev': current_forum.googleWebDeveloper,
    'page_ga_id': current_forum.googleAnalyticsId,
    'page_logo_url': ''
} %}

{% block stylesheets %}
    {{ parent() }}
    {# Required code! Decoda uses it for alignment #}
    <style>
        .align-left {
            text-align: left;
        }

        .align-center {
            text-align: center;
        }

        .align-right {
            text-align: right;
        }
    </style>
{% endblock %}

{% block title %}{{ current_thread.topic }} | {{ service.page_name }}{% endblock %}

{% block header %}
    <div class="container">
        <h1 class="mt-4 mb-2 pb-2 border-bottom">{{ current_thread.topic }}</h1>
    </div>
{% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path('forum_index', {'forum': current_forum.url}) }}">{{ 'service_thread.breadcrumb.home'|trans }}</a></li>
                {% for key,level in breadcrumb %}
                    {% if level.type == 1 %}
                        <li class="breadcrumb-item"><a href="{{ path('forum_board', {'forum': current_forum.url, 'board': level.id}) }}">{{ level.title }}</a></li>
                    {% endif %}
                {% endfor %}
                <li class="breadcrumb-item"><a href="{{ path('forum_board', {'forum': current_forum.url, 'board': current_board.id}) }}">{{ current_board.title }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ current_thread.topic }}</li>
            </ol>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% if posts|length > 0 %}
            {% for post in posts %}
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover table-sm">
                        <tbody>
                            <tr class="d-flex">
                                <td class="col">
                                    <p class="text-center"><a href="{{ path('user', {'username': post.user.username}) }}">{{ post.user.username }}</a></p>
                                    <div class="text-center mb-3">
                                        <a href="{{ path('user', {'username': post.user.username}) }}">
                                            <img src="{{ oauth_url }}/api/get_img?user_id={{ post.user.id }}&height=200&width=200" class="img-fluid rounded" alt="">
                                        </a>
                                    </div>
                                    {% if app.user is not empty and app.user.id == post.user.id %}
                                        {# TODO: Add edit function #}
                                        <p><a href="#edit" class="btn btn-primary btn-sm">{{ 'service_thread.edit'|trans }}</a></p>
                                    {% endif %}
                                </td>
                                <td class="col-10">{{ post.formattedMessage|raw }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            {% endfor %}
        {% endif %}

        <div class="row">
            <div class="col-md-8">
                {% if pagination.pages_count > 1 %}
                    <ul class="pagination" style="margin:0">
                        {# Reference: http://www.strangerstudios.com/sandbox/pagination/diggstyle.php #}
                        {# Previous Page #}
                        {% if pagination.current_page > 1 %}
                            <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': pagination.previous_page, 'show': pagination.item_limit}) }}" aria-label="{{ 'service_thread.pagination.previous'|trans }}"><span aria-hidden="true">&laquo;</span></a></li>
                        {% else %}
                            <li class="disabled"><a aria-label="{{ 'service_thread.pagination.previous'|trans }}"><span aria-hidden="true">&laquo;</span></a></li>
                        {% endif %}

                        {# Pager #}
                        {% if pagination.pages_count < (7 + (pagination.adjacents * 2)) %}{# not enough pages to bother breaking it up #}
                            {% set page_counter = 1 %}
                            {% for i in page_counter..pagination.pages_count %}
                                {% if page_counter == pagination.current_page %}
                                    <li class="active"><a>{{ page_counter }}</a></li>
                                {% else %}
                                    <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': page_counter, 'show': pagination.item_limit}) }}">{{ page_counter }}</a></li>
                                {% endif %}
                                {% set page_counter = page_counter + 1 %}
                            {% endfor %}
                        {% elseif pagination.pages_count >= (7 + (pagination.adjacents * 2)) %}{# enough pages to hide some #}

                            {# close to beginning; only hide later pages #}
                            {% if pagination.current_page < (1 + (pagination.adjacents * 3)) %}
                                {% set page_counter = 1 %}
                                {% for i in page_counter..(4 +(pagination.adjacents * 2)) %}
                                    {% if page_counter == pagination.current_page %}
                                        <li class="active"><a>{{ page_counter }}</a></li>
                                    {% else %}
                                        <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': page_counter, 'show': pagination.item_limit}) }}">{{ page_counter }}</a></li>
                                    {% endif %}
                                    {% set page_counter = page_counter + 1 %}
                                {% endfor %}

                                <li class="disabled"><a>...</a></li>
                                <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': pagination.last_page_m1, 'show': pagination.item_limit}) }}">{{ pagination.last_page_m1 }}</a></li>
                                <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': pagination.pages_count, 'show': pagination.item_limit}) }}">{{ pagination.pages_count }}</a></li>

                            {# in middle; hide some front and some back #}
                            {% elseif (pagination.pages_count - (pagination.adjacents * 2)) > pagination.current_page and pagination.current_page > (pagination.adjacents * 3) %}
                                <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': 1, 'show': pagination.item_limit}) }}">1</a></li>
                                <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': 2, 'show': pagination.item_limit}) }}">2</a></li>
                                <li class="disabled"><a>...</a></li>

                                {% set page_counter = pagination.current_page - pagination.adjacents %}
                                {% for i in page_counter..(pagination.current_page + pagination.adjacents) %}
                                    {% if page_counter == pagination.current_page %}
                                        <li class="active"><a>{{ page_counter }}</a></li>
                                    {% else %}
                                        <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': page_counter, 'show': pagination.item_limit}) }}">{{ page_counter }}</a></li>
                                    {% endif %}
                                    {% set page_counter = page_counter + 1 %}
                                {% endfor %}

                                <li class="disabled"><a>...</a></li>
                                <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': pagination.last_page_m1, 'show': pagination.item_limit}) }}">{{ pagination.last_page_m1 }}</a></li>
                                <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': pagination.pages_count, 'show': pagination.item_limit}) }}">{{ pagination.pages_count }}</a></li>

                            {# close to end; only hide early pages #}
                            {% else %}
                                <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': 1, 'show': pagination.item_limit}) }}">1</a></li>
                                <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': 2, 'show': pagination.item_limit}) }}">2</a></li>
                                <li class="disabled"><a>...</a></li>

                                {% set page_counter = pagination.pages_count - (1 + (pagination.adjacents * 3)) %}
                                {% for i in page_counter..pagination.pages_count %}
                                    {% if page_counter == pagination.current_page %}
                                        <li class="active"><a>{{ page_counter }}</a></li>
                                    {% else %}
                                        <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': page_counter, 'show': pagination.item_limit}) }}">{{ page_counter }}</a></li>
                                    {% endif %}
                                    {% set page_counter = page_counter + 1 %}
                                {% endfor %}

                            {% endif %}
                        {% endif %}

                        {# Next page #}
                        {% if pagination.current_page < pagination.last_page_m1 %}
                            <li><a href="{{ path('forum_thread', {'forum': current_forum.url, 'thread': current_thread.id, 'page': pagination.next_page, 'show': pagination.item_limit}) }}" aria-label="{{ 'service_thread.pagination.next'|trans }}"><span aria-hidden="true">&raquo;</span></a></li>
                        {% else %}
                            <li class="disabled"><a aria-label="{{ 'service_thread.pagination.next'|trans }}"><span aria-hidden="true">&raquo;</span></a></li>
                        {% endif %}

                    </ul>
                {% endif %}
            </div>
            {% if app.user is not empty %}
                <div class="col-md-4">
                    <p class="text-right"><a href="{{ path('forum_create_post', {'forum': current_forum.url, 'thread': current_thread.id}) }}" class="btn btn-primary">{{ 'service_thread.reply'|trans }}</a></p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}